//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("${appName}.{appenderName}")]
[assembly: AssemblyProduct("Gelf4Net.UdpAppender")]
[assembly: AssemblyVersion("1.0.0.17")]
[assembly: AssemblyFileVersion("1.0.0.17")]
[assembly: AssemblyInformationalVersion("1.0.0.17")]
[assembly: AssemblyCopyright("Copyright � 2017")]

