//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Gelf4Net.HttpAppender")]
[assembly: AssemblyProduct("Gelf4Net.HttpAppender")]
[assembly: AssemblyVersion("1.0.0.11")]
[assembly: AssemblyFileVersion("1.0.0.11")]
[assembly: AssemblyInformationalVersion("1.0.0.11")]
[assembly: AssemblyCopyright("MIT 2017")]

