//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Gelf4Net")]
[assembly: AssemblyProduct("Gelf4Net")]
[assembly: AssemblyVersion("3.0.0.5")]
[assembly: AssemblyFileVersion("3.0.0.5")]
[assembly: AssemblyInformationalVersion("3.0.0.5")]
[assembly: AssemblyCopyright("MIT 2017")]

