//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("${appName}.{appenderName}")]
[assembly: AssemblyProduct("Gelf4Net.AmqpAppender")]
[assembly: AssemblyVersion("1.0.0.24")]
[assembly: AssemblyFileVersion("1.0.0.24")]
[assembly: AssemblyInformationalVersion("1.0.0.24")]
[assembly: AssemblyCopyright("Copyright � 2017")]

